### ISSUE TITLE
run 함수 가독성이,,,

### ISSUE THREAD

**Issue by yeonjujeong** [yeonjujeong/ERICA_ChessGame#2]
run 함수안에 들어가야하는 장기알 알고리즘(?)이 너무 많아서 가독성이 조금 떨어지는 것 같은데 
어떻게 하면 좋을까요.,,,,,

**Comment by yejin00** [comment]
차 함수는 따로 def cha()로 빼서 만들고 병 함수도 def jjol()로 따로 빼고 앞으로 만들 포도 def po()이렇게 함수를 장기 알 마다 따로 만들면 가독성이 더욱 좋아지지 않을까요?

**Comment by yeonjujeong** [comment]
아 그런것같네요!! 그렇게 수정해보았어요!! 가독성이 훨신 good!!!
