### ISSUE TITLE
병과 졸

### ISSUE THREAD

**Issue by Kim-jeongmin** [yeonjujeong/ERICA_ChessGame#4]
병이랑 졸이랑 원래 앞으로 한칸이랑 양옆 한칸씩 가는데 전에 코드는 그게 아니어서 계속 수정했는데 자꾸 while 문에 걸려서 거기에 못둔다고 계속 뜨는데 이거 어떡해요??????

**Comment by yeonjujeong** [comment]
뭐가 계속 못둔다고 뜨는거에요??? 원래 갈 수 있는 자린데 못둔다고 뜨는 건가요??

**Comment by yeonjujeong** [comment]
뒤로 못가는 건 수정했어요!!! 다시 해보고 오류뜨는거 말씀해주세엽!!!

**Comment by Kim-jeongmin** [comment]
다 수정했습니다. 감사합니다~^
